trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
    customRegistry: 'useFeed'
    customFeed: '79153133-3e91-49a4-8d53-801031287fc8/688c6563-5ac9-4d2f-ac91-2026989e38ea'